# version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: helloapp_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: helloapp
      MYSQL_USER: hellouser
      MYSQL_PASSWORD: hellopassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - helloapp-network

volumes:
  mysql_data:

networks:
  helloapp-network:
    external: true